name: portfolio_web
description: "이혜성의 포트폴리오 root app"
resolution: workspace

version: 1.0.3+3

environment:
  sdk: ^3.10.3

dependencies:
  convention:
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true